Create Database BookDB;
use BookDB;
create table User (
	Id INT not null auto_increment primary key,
	Name VARCHAR(50) not null,
	Email VARCHAR(50) not null unique,
	Password VARCHAR(50) not null
);
insert into User (Id, Name, Email, Password) values (1, 'Josefa Carty', 'jcarty0@macromedia.com', 'm2QDW0ZGzVy');
insert into User (Id, Name, Email, Password) values (2, 'Teodora Kerrod', 'tkerrod1@mit.edu', 'AAnbmdt');
insert into User (Id, Name, Email, Password) values (3, 'Robena O''Tuohy', 'rotuohy2@ezinearticles.com', 'MSmApU');
insert into User (Id, Name, Email, Password) values (4, 'Alvy Rizzardi', 'arizzardi3@about.com', '6QTN0z4k7kt');
insert into User (Id, Name, Email, Password) values (5, 'Craggy Kisbee', 'ckisbee4@ca.gov', '9EBV9yQBE');
insert into User (Id, Name, Email, Password) values (6, 'Richy Barnshaw', 'rbarnshaw5@weebly.com', 'FyN9dBWUPe06');
insert into User (Id, Name, Email, Password) values (7, 'Arnold Rodda', 'arodda6@springer.com', 'KzlLr8F2');
insert into User (Id, Name, Email, Password) values (8, 'Guilbert Robjant', 'grobjant7@guardian.co.uk', 'oqQemPu5m');
insert into User (Id, Name, Email, Password) values (9, 'Bernardo Foan', 'bfoan8@telegraph.co.uk', 'loFvxT');
insert into User (Id, Name, Email, Password) values (10, 'Koressa Phipps', 'kphipps9@surveymonkey.com', '1lPvuWiq');

create table Book (
	Id INT not null primary key auto_increment,
	Title VARCHAR(250) not null,
	Author VARCHAR(250) not null,
	Price DECIMAL(6,2),
	Rating INT,
	PublishDate DATE,
	URL VARCHAR(4000),
	Description TEXT
);
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (1, 'Sheltering Sky, The', 'Rene Fenich', 813.43, 3, '2022-07-15', 'https://stumbleupon.com/mauris.xml?vehicula=elit&condimentum=proin&curabitur=interdum&in=mauris&libero=non&ut=ligula&massa=pellentesque&volutpat=ultrices&convallis=phasellus&morbi=id&odio=sapien&odio=in&elementum=sapien&eu=iaculis&interdum=congue&eu=vivamus&tincidunt=metus&in=arcu&leo=adipiscing&maecenas=molestie&pulvinar=hendrerit&lobortis=at&est=vulputate&phasellus=vitae&sit=nisl&amet=aenean&erat=lectus&nulla=pellentesque&tempus=eget&vivamus=nunc&in=donec&felis=quis&eu=orci&sapien=eget&cursus=orci&vestibulum=vehicula&proin=condimentum&eu=curabitur&mi=in&nulla=libero&ac=ut&enim=massa&in=volutpat&tempor=convallis&turpis=morbi&nec=odio&euismod=odio&scelerisque=elementum&quam=eu&turpis=interdum&adipiscing=eu&lorem=tincidunt&vitae=in&mattis=leo&nibh=maecenas&ligula=pulvinar&nec=lobortis&sem=est&duis=phasellus&aliquam=sit&convallis=amet&nunc=erat&proin=nulla&at=tempus&turpis=vivamus&a=in&pede=felis&posuere=eu&nonummy=sapien&integer=cursus&non=vestibulum&velit=proin&donec=eu&diam=mi&neque=nulla&vestibulum=ac&eget=enim&vulputate=in&ut=tempor&ultrices=turpis&vel=nec&augue=euismod&vestibulum=scelerisque&ante=quam&ipsum=turpis&primis=adipiscing&in=lorem&faucibus=vitae&orci=mattis&luctus=nibh&et=ligula&ultrices=nec&posuere=sem&cubilia=duis', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.

Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (2, 'Dick Tracy', 'Shae Glisane', 163.92, 5, '2023-01-23', 'https://abc.net.au/erat/curabitur/gravida.aspx?sit=ante&amet=vivamus&consectetuer=tortor&adipiscing=duis&elit=mattis&proin=egestas&risus=metus&praesent=aenean&lectus=fermentum&vestibulum=donec&quam=ut&sapien=mauris&varius=eget&ut=massa&blandit=tempor&non=convallis&interdum=nulla&in=neque&ante=libero&vestibulum=convallis&ante=eget&ipsum=eleifend&primis=luctus&in=ultricies&faucibus=eu&orci=nibh&luctus=quisque', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (3, 'Johnny Was', 'Missie Bandey', 465.93, 2, '2022-08-14', 'https://latimes.com/vel/pede/morbi/porttitor/lorem/id.html?justo=erat&nec=id&condimentum=mauris&neque=vulputate&sapien=elementum&placerat=nullam&ante=varius&nulla=nulla&justo=facilisi&aliquam=cras&quis=non&turpis=velit&eget=nec&elit=nisi&sodales=vulputate&scelerisque=nonummy&mauris=maecenas&sit=tincidunt&amet=lacus&eros=at&suspendisse=velit&accumsan=vivamus&tortor=vel&quis=nulla&turpis=eget&sed=eros&ante=elementum&vivamus=pellentesque&tortor=quisque&duis=porta&mattis=volutpat&egestas=erat&metus=quisque&aenean=erat&fermentum=eros&donec=viverra&ut=eget&mauris=congue&eget=eget&massa=semper&tempor=rutrum&convallis=nulla&nulla=nunc&neque=purus&libero=phasellus&convallis=in&eget=felis&eleifend=donec&luctus=semper&ultricies=sapien&eu=a&nibh=libero&quisque=nam&id=dui&justo=proin&sit=leo&amet=odio&sapien=porttitor&dignissim=id&vestibulum=consequat&vestibulum=in&ante=consequat&ipsum=ut&primis=nulla&in=sed&faucibus=accumsan&orci=felis&luctus=ut&et=at&ultrices=dolor&posuere=quis&cubilia=odio&curae=consequat&nulla=varius&dapibus=integer', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.

In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (4, 'Tucker & Dale vs Evil', 'Cacilia Provis', 348.18, 3, '2023-01-16', 'https://guardian.co.uk/ut/odio/cras/mi/pede.aspx?arcu=massa&adipiscing=id&molestie=lobortis&hendrerit=convallis&at=tortor&vulputate=risus&vitae=dapibus&nisl=augue&aenean=vel&lectus=accumsan&pellentesque=tellus&eget=nisi&nunc=eu&donec=orci&quis=mauris&orci=lacinia&eget=sapien&orci=quis&vehicula=libero&condimentum=nullam&curabitur=sit&in=amet&libero=turpis&ut=elementum&massa=ligula&volutpat=vehicula&convallis=consequat&morbi=morbi&odio=a&odio=ipsum&elementum=integer&eu=a&interdum=nibh&eu=in&tincidunt=quis&in=justo&leo=maecenas&maecenas=rhoncus&pulvinar=aliquam&lobortis=lacus&est=morbi&phasellus=quis&sit=tortor&amet=id&erat=nulla&nulla=ultrices&tempus=aliquet&vivamus=maecenas&in=leo&felis=odio&eu=condimentum&sapien=id&cursus=luctus&vestibulum=nec&proin=molestie&eu=sed&mi=justo&nulla=pellentesque&ac=viverra&enim=pede&in=ac&tempor=diam&turpis=cras&nec=pellentesque&euismod=volutpat&scelerisque=dui&quam=maecenas&turpis=tristique&adipiscing=est&lorem=et&vitae=tempus&mattis=semper&nibh=est&ligula=quam&nec=pharetra&sem=magna&duis=ac&aliquam=consequat', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (5, 'Legacy of Rage', 'Emelia Thorington', 97.67, 5, '2022-03-06', 'http://wisc.edu/potenti/cras/in/purus.png?convallis=venenatis&morbi=non&odio=sodales&odio=sed&elementum=tincidunt&eu=eu&interdum=felis&eu=fusce&tincidunt=posuere&in=felis&leo=sed&maecenas=lacus&pulvinar=morbi&lobortis=sem&est=mauris&phasellus=laoreet&sit=ut&amet=rhoncus&erat=aliquet&nulla=pulvinar&tempus=sed&vivamus=nisl&in=nunc&felis=rhoncus&eu=dui&sapien=vel&cursus=sem&vestibulum=sed&proin=sagittis&eu=nam&mi=congue&nulla=risus&ac=semper', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (6, 'Tales from the Script', 'Orel Trenholm', 84.13, 5, '2023-01-09', 'http://thetimes.co.uk/imperdiet.jsp?convallis=dapibus&nunc=duis&proin=at&at=velit&turpis=eu&a=est&pede=congue&posuere=elementum&nonummy=in&integer=hac&non=habitasse&velit=platea&donec=dictumst&diam=morbi&neque=vestibulum&vestibulum=velit&eget=id&vulputate=pretium&ut=iaculis&ultrices=diam&vel=erat&augue=fermentum&vestibulum=justo&ante=nec&ipsum=condimentum&primis=neque&in=sapien&faucibus=placerat&orci=ante&luctus=nulla&et=justo&ultrices=aliquam&posuere=quis&cubilia=turpis&curae=eget&donec=elit&pharetra=sodales&magna=scelerisque&vestibulum=mauris&aliquet=sit&ultrices=amet&erat=eros&tortor=suspendisse&sollicitudin=accumsan&mi=tortor&sit=quis&amet=turpis&lobortis=sed&sapien=ante&sapien=vivamus&non=tortor&mi=duis&integer=mattis', 'Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (7, 'Daddy and Them', 'Bruno Witson', 320.69, 5, '2022-09-25', 'https://over-blog.com/ac/leo/pellentesque/ultrices/mattis/odio.xml?nullam=purus&orci=phasellus&pede=in&venenatis=felis&non=donec&sodales=semper&sed=sapien&tincidunt=a&eu=libero&felis=nam&fusce=dui&posuere=proin&felis=leo&sed=odio&lacus=porttitor&morbi=id&sem=consequat&mauris=in&laoreet=consequat&ut=ut&rhoncus=nulla&aliquet=sed&pulvinar=accumsan&sed=felis&nisl=ut&nunc=at&rhoncus=dolor&dui=quis&vel=odio&sem=consequat&sed=varius&sagittis=integer&nam=ac&congue=leo&risus=pellentesque&semper=ultrices&porta=mattis&volutpat=odio&quam=donec&pede=vitae&lobortis=nisi&ligula=nam&sit=ultrices&amet=libero&eleifend=non&pede=mattis&libero=pulvinar&quis=nulla&orci=pede&nullam=ullamcorper&molestie=augue&nibh=a&in=suscipit&lectus=nulla&pellentesque=elit&at=ac&nulla=nulla&suspendisse=sed&potenti=vel&cras=enim&in=sit', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (8, 'Down to the Cellar (Do pivnice)', 'Rinaldo Trafford', 224.07, 0, '2022-05-28', 'http://sciencedirect.com/tellus.xml?vitae=faucibus&consectetuer=orci&eget=luctus&rutrum=et&at=ultrices&lorem=posuere&integer=cubilia&tincidunt=curae&ante=donec&vel=pharetra&ipsum=magna&praesent=vestibulum&blandit=aliquet&lacinia=ultrices&erat=erat&vestibulum=tortor&sed=sollicitudin&magna=mi&at=sit&nunc=amet&commodo=lobortis&placerat=sapien', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (9, 'Gang''s All Here, The', 'Dominique Barz', 637.6, 2, '2022-12-07', 'http://google.pl/ante/ipsum/primis/in/faucibus/orci.jpg?ultrices=mollis&posuere=molestie&cubilia=lorem&curae=quisque&nulla=ut&dapibus=erat&dolor=curabitur&vel=gravida&est=nisi&donec=at&odio=nibh&justo=in&sollicitudin=hac&ut=habitasse&suscipit=platea&a=dictumst&feugiat=aliquam&et=augue&eros=quam&vestibulum=sollicitudin&ac=vitae&est=consectetuer&lacinia=eget&nisi=rutrum&venenatis=at&tristique=lorem&fusce=integer&congue=tincidunt&diam=ante&id=vel&ornare=ipsum&imperdiet=praesent&sapien=blandit&urna=lacinia', 'Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (10, 'Eyes Wide Shut', 'Arty Bruinsma', 108.04, 2, '2022-05-23', 'https://tripod.com/eget/rutrum/at.jsp?pede=vel&libero=nulla&quis=eget&orci=eros&nullam=elementum&molestie=pellentesque', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (11, 'Son in Law', 'Dan O''Hear', 405.96, 0, '2023-01-02', 'https://timesonline.co.uk/fusce/congue/diam/id/ornare/imperdiet.html?mauris=hac&sit=habitasse&amet=platea&eros=dictumst&suspendisse=morbi&accumsan=vestibulum&tortor=velit&quis=id&turpis=pretium&sed=iaculis&ante=diam&vivamus=erat', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (12, 'Violent Saturday', 'Cynthia Scade', 615.89, 2, '2022-05-16', 'https://si.edu/ac/est.js?posuere=id&felis=ligula&sed=suspendisse&lacus=ornare&morbi=consequat&sem=lectus&mauris=in&laoreet=est&ut=risus&rhoncus=auctor&aliquet=sed&pulvinar=tristique&sed=in&nisl=tempus&nunc=sit&rhoncus=amet&dui=sem&vel=fusce&sem=consequat&sed=nulla&sagittis=nisl&nam=nunc&congue=nisl&risus=duis&semper=bibendum&porta=felis&volutpat=sed&quam=interdum&pede=venenatis&lobortis=turpis&ligula=enim&sit=blandit&amet=mi&eleifend=in&pede=porttitor&libero=pede&quis=justo&orci=eu&nullam=massa&molestie=donec&nibh=dapibus&in=duis&lectus=at&pellentesque=velit&at=eu&nulla=est&suspendisse=congue&potenti=elementum&cras=in&in=hac&purus=habitasse&eu=platea&magna=dictumst&vulputate=morbi&luctus=vestibulum&cum=velit&sociis=id&natoque=pretium&penatibus=iaculis&et=diam&magnis=erat&dis=fermentum&parturient=justo&montes=nec&nascetur=condimentum&ridiculus=neque&mus=sapien&vivamus=placerat&vestibulum=ante&sagittis=nulla&sapien=justo&cum=aliquam&sociis=quis', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (13, 'Saragossa Manuscript, The (Rekopis znaleziony w Saragossie)', 'Kacie Morford', 583.36, 0, '2022-06-24', 'https://msn.com/blandit/lacinia/erat/vestibulum.js?erat=odio&quisque=curabitur&erat=convallis&eros=duis&viverra=consequat&eget=dui&congue=nec&eget=nisi&semper=volutpat&rutrum=eleifend', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.

Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (14, 'Down in the Valley', 'Em Orwell', 964.09, 5, '2022-02-16', 'http://chron.com/neque/libero/convallis/eget.aspx?volutpat=vulputate&sapien=vitae&arcu=nisl&sed=aenean&augue=lectus&aliquam=pellentesque&erat=eget&volutpat=nunc&in=donec&congue=quis&etiam=orci&justo=eget&etiam=orci&pretium=vehicula&iaculis=condimentum&justo=curabitur&in=in&hac=libero&habitasse=ut&platea=massa&dictumst=volutpat&etiam=convallis&faucibus=morbi&cursus=odio&urna=odio&ut=elementum&tellus=eu&nulla=interdum&ut=eu&erat=tincidunt&id=in&mauris=leo&vulputate=maecenas&elementum=pulvinar&nullam=lobortis&varius=est&nulla=phasellus&facilisi=sit&cras=amet&non=erat&velit=nulla&nec=tempus&nisi=vivamus&vulputate=in&nonummy=felis&maecenas=eu&tincidunt=sapien&lacus=cursus&at=vestibulum&velit=proin&vivamus=eu&vel=mi&nulla=nulla&eget=ac&eros=enim&elementum=in&pellentesque=tempor&quisque=turpis&porta=nec&volutpat=euismod&erat=scelerisque&quisque=quam&erat=turpis&eros=adipiscing&viverra=lorem&eget=vitae&congue=mattis&eget=nibh&semper=ligula&rutrum=nec&nulla=sem', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.

Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (15, 'Carcasses', 'Annecorinne Klebes', 633.13, 1, '2022-08-26', 'http://xrea.com/est.html?nulla=donec&facilisi=posuere&cras=metus&non=vitae&velit=ipsum&nec=aliquam&nisi=non&vulputate=mauris&nonummy=morbi&maecenas=non&tincidunt=lectus&lacus=aliquam&at=sit&velit=amet&vivamus=diam&vel=in&nulla=magna&eget=bibendum&eros=imperdiet&elementum=nullam&pellentesque=orci&quisque=pede&porta=venenatis&volutpat=non&erat=sodales&quisque=sed&erat=tincidunt&eros=eu&viverra=felis&eget=fusce&congue=posuere&eget=felis&semper=sed&rutrum=lacus&nulla=morbi&nunc=sem&purus=mauris&phasellus=laoreet&in=ut&felis=rhoncus&donec=aliquet&semper=pulvinar&sapien=sed&a=nisl&libero=nunc&nam=rhoncus&dui=dui&proin=vel&leo=sem&odio=sed&porttitor=sagittis&id=nam&consequat=congue&in=risus&consequat=semper&ut=porta&nulla=volutpat&sed=quam', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (16, 'Modify ', 'Herby Gorler', 428.9, 4, '2022-10-28', 'http://uiuc.edu/eu/magna.aspx?sit=ultrices&amet=posuere&diam=cubilia&in=curae&magna=mauris&bibendum=viverra&imperdiet=diam&nullam=vitae&orci=quam&pede=suspendisse&venenatis=potenti&non=nullam&sodales=porttitor&sed=lacus&tincidunt=at&eu=turpis&felis=donec&fusce=posuere&posuere=metus&felis=vitae&sed=ipsum&lacus=aliquam&morbi=non&sem=mauris&mauris=morbi&laoreet=non&ut=lectus&rhoncus=aliquam&aliquet=sit&pulvinar=amet&sed=diam&nisl=in&nunc=magna&rhoncus=bibendum&dui=imperdiet&vel=nullam&sem=orci&sed=pede&sagittis=venenatis&nam=non&congue=sodales&risus=sed&semper=tincidunt', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.

Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (17, 'Wooden Bridge, The', 'Reine Gumb', 846.8, 4, '2023-01-20', 'https://tinyurl.com/molestie/hendrerit/at/vulputate/vitae/nisl/aenean.jsp?quam=fusce&a=consequat&odio=nulla&in=nisl&hac=nunc&habitasse=nisl&platea=duis&dictumst=bibendum&maecenas=felis&ut=sed&massa=interdum&quis=venenatis&augue=turpis&luctus=enim&tincidunt=blandit&nulla=mi&mollis=in&molestie=porttitor&lorem=pede&quisque=justo&ut=eu&erat=massa&curabitur=donec&gravida=dapibus&nisi=duis&at=at&nibh=velit&in=eu&hac=est&habitasse=congue&platea=elementum&dictumst=in&aliquam=hac&augue=habitasse&quam=platea&sollicitudin=dictumst&vitae=morbi&consectetuer=vestibulum&eget=velit', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (18, 'Live Free or Die Hard', 'Marline Coghlin', 57.29, 3, '2022-08-21', 'https://google.nl/pellentesque/at/nulla/suspendisse/potenti/cras.html?aliquet=nibh&massa=ligula&id=nec&lobortis=sem&convallis=duis&tortor=aliquam&risus=convallis&dapibus=nunc&augue=proin&vel=at&accumsan=turpis&tellus=a&nisi=pede&eu=posuere&orci=nonummy&mauris=integer&lacinia=non&sapien=velit&quis=donec&libero=diam&nullam=neque&sit=vestibulum&amet=eget&turpis=vulputate&elementum=ut&ligula=ultrices&vehicula=vel&consequat=augue&morbi=vestibulum&a=ante&ipsum=ipsum&integer=primis&a=in&nibh=faucibus&in=orci&quis=luctus&justo=et&maecenas=ultrices&rhoncus=posuere&aliquam=cubilia&lacus=curae&morbi=donec&quis=pharetra&tortor=magna&id=vestibulum&nulla=aliquet&ultrices=ultrices&aliquet=erat&maecenas=tortor&leo=sollicitudin&odio=mi&condimentum=sit&id=amet&luctus=lobortis&nec=sapien&molestie=sapien&sed=non&justo=mi&pellentesque=integer&viverra=ac&pede=neque&ac=duis&diam=bibendum&cras=morbi&pellentesque=non&volutpat=quam&dui=nec&maecenas=dui&tristique=luctus&est=rutrum&et=nulla&tempus=tellus&semper=in&est=sagittis&quam=dui&pharetra=vel&magna=nisl', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.

Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.

Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (19, 'Hunted City', 'Hayley Gorriessen', 639.14, 4, '2022-08-22', 'https://boston.com/turpis/donec/posuere.aspx?consequat=luctus&varius=tincidunt&integer=nulla&ac=mollis&leo=molestie&pellentesque=lorem&ultrices=quisque&mattis=ut&odio=erat&donec=curabitur&vitae=gravida&nisi=nisi&nam=at&ultrices=nibh&libero=in&non=hac&mattis=habitasse&pulvinar=platea&nulla=dictumst&pede=aliquam&ullamcorper=augue&augue=quam&a=sollicitudin&suscipit=vitae&nulla=consectetuer&elit=eget&ac=rutrum&nulla=at&sed=lorem&vel=integer&enim=tincidunt&sit=ante&amet=vel&nunc=ipsum&viverra=praesent&dapibus=blandit&nulla=lacinia&suscipit=erat&ligula=vestibulum&in=sed&lacus=magna&curabitur=at&at=nunc&ipsum=commodo&ac=placerat&tellus=praesent&semper=blandit&interdum=nam&mauris=nulla&ullamcorper=integer&purus=pede&sit=justo&amet=lacinia&nulla=eget&quisque=tincidunt&arcu=eget&libero=tempus&rutrum=vel&ac=pede&lobortis=morbi&vel=porttitor&dapibus=lorem&at=id&diam=ligula&nam=suspendisse&tristique=ornare&tortor=consequat&eu=lectus', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (20, 'Sammy and Rosie Get Laid', 'Lothario Nobbs', 429.46, 2, '2022-05-31', 'https://studiopress.com/etiam/pretium/iaculis/justo/in/hac/habitasse.js?proin=vitae&eu=nisl&mi=aenean&nulla=lectus&ac=pellentesque&enim=eget&in=nunc&tempor=donec&turpis=quis&nec=orci&euismod=eget&scelerisque=orci&quam=vehicula&turpis=condimentum&adipiscing=curabitur&lorem=in&vitae=libero&mattis=ut&nibh=massa&ligula=volutpat&nec=convallis&sem=morbi&duis=odio&aliquam=odio&convallis=elementum&nunc=eu&proin=interdum&at=eu&turpis=tincidunt&a=in&pede=leo&posuere=maecenas&nonummy=pulvinar&integer=lobortis&non=est&velit=phasellus&donec=sit&diam=amet&neque=erat&vestibulum=nulla&eget=tempus&vulputate=vivamus&ut=in&ultrices=felis&vel=eu&augue=sapien&vestibulum=cursus&ante=vestibulum&ipsum=proin&primis=eu&in=mi&faucibus=nulla&orci=ac&luctus=enim&et=in&ultrices=tempor&posuere=turpis&cubilia=nec&curae=euismod&donec=scelerisque&pharetra=quam&magna=turpis&vestibulum=adipiscing&aliquet=lorem&ultrices=vitae&erat=mattis&tortor=nibh&sollicitudin=ligula&mi=nec&sit=sem&amet=duis&lobortis=aliquam&sapien=convallis&sapien=nunc&non=proin', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (21, 'Brotherhood, The', 'Lucie Sanzio', 338.62, 0, '2022-11-14', 'http://is.gd/maecenas/pulvinar/lobortis/est/phasellus/sit.xml?mi=fusce&sit=posuere&amet=felis&lobortis=sed&sapien=lacus&sapien=morbi&non=sem&mi=mauris&integer=laoreet&ac=ut&neque=rhoncus&duis=aliquet&bibendum=pulvinar&morbi=sed', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (22, 'Black Robe', 'Tyler Huge', 833.15, 5, '2022-06-14', 'https://godaddy.com/neque/vestibulum/eget/vulputate/ut.png?in=dui&lacus=vel&curabitur=nisl', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (23, 'Sunnyside', 'Saba Roelvink', 314.43, 4, '2022-09-03', 'https://soup.io/vitae/nisl/aenean/lectus/pellentesque/eget/nunc.js?sapien=vestibulum&arcu=ante&sed=ipsum&augue=primis&aliquam=in&erat=faucibus&volutpat=orci&in=luctus&congue=et&etiam=ultrices&justo=posuere&etiam=cubilia&pretium=curae&iaculis=mauris&justo=viverra&in=diam&hac=vitae&habitasse=quam&platea=suspendisse&dictumst=potenti&etiam=nullam&faucibus=porttitor&cursus=lacus&urna=at&ut=turpis&tellus=donec&nulla=posuere&ut=metus&erat=vitae&id=ipsum&mauris=aliquam&vulputate=non&elementum=mauris&nullam=morbi&varius=non&nulla=lectus&facilisi=aliquam&cras=sit&non=amet&velit=diam&nec=in&nisi=magna&vulputate=bibendum&nonummy=imperdiet&maecenas=nullam&tincidunt=orci&lacus=pede&at=venenatis&velit=non', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (24, 'Tadpole', 'Saudra Croughan', 188.1, 3, '2022-09-15', 'https://imgur.com/lobortis/vel/dapibus/at.html?morbi=praesent&quis=blandit&tortor=nam&id=nulla&nulla=integer&ultrices=pede&aliquet=justo&maecenas=lacinia&leo=eget&odio=tincidunt&condimentum=eget&id=tempus&luctus=vel&nec=pede&molestie=morbi&sed=porttitor&justo=lorem&pellentesque=id&viverra=ligula&pede=suspendisse&ac=ornare&diam=consequat&cras=lectus&pellentesque=in&volutpat=est&dui=risus&maecenas=auctor&tristique=sed&est=tristique&et=in&tempus=tempus&semper=sit&est=amet&quam=sem&pharetra=fusce&magna=consequat&ac=nulla&consequat=nisl&metus=nunc&sapien=nisl&ut=duis&nunc=bibendum&vestibulum=felis&ante=sed&ipsum=interdum&primis=venenatis&in=turpis&faucibus=enim&orci=blandit&luctus=mi&et=in&ultrices=porttitor&posuere=pede&cubilia=justo&curae=eu&mauris=massa&viverra=donec&diam=dapibus&vitae=duis&quam=at&suspendisse=velit&potenti=eu&nullam=est&porttitor=congue&lacus=elementum&at=in&turpis=hac&donec=habitasse&posuere=platea&metus=dictumst&vitae=morbi&ipsum=vestibulum&aliquam=velit&non=id&mauris=pretium&morbi=iaculis&non=diam', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.');
insert into Book (Id, Title, Author, Price, Rating, PublishDate, URL, Description) values (25, 'Takeshis''', 'Dana Rohloff', 1.95, 5, '2022-07-05', 'http://imageshack.us/pharetra/magna/ac/consequat/metus.js?vestibulum=fusce&ante=posuere&ipsum=felis&primis=sed&in=lacus&faucibus=morbi&orci=sem&luctus=mauris&et=laoreet&ultrices=ut&posuere=rhoncus&cubilia=aliquet&curae=pulvinar&nulla=sed&dapibus=nisl&dolor=nunc&vel=rhoncus&est=dui&donec=vel&odio=sem&justo=sed&sollicitudin=sagittis&ut=nam&suscipit=congue&a=risus&feugiat=semper&et=porta&eros=volutpat&vestibulum=quam&ac=pede&est=lobortis&lacinia=ligula&nisi=sit&venenatis=amet&tristique=eleifend&fusce=pede&congue=libero&diam=quis&id=orci&ornare=nullam&imperdiet=molestie&sapien=nibh', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
